port select clang mp-clang-7.0
port select cython cython37
port select gcc mp-gcc8
port select llvm mp-llvm-7.0
port select mpi openmpi-gcc8-fortran
port select nosetests nosetests37
port select postgresql postgresql10
port select pygments py37-pygments
port select python python27
port select python2 python27
port select python3 python37
port select sphinx py37-sphinx
